SET FOREIGN_KEY_CHECKS = 0;

DROP INDEX picture_fi_1 ON picture;
CREATE INDEX IDX_16DB4F89A76ED395 ON picture (user_id);
ALTER TABLE post CHANGE text text VARCHAR(255) DEFAULT NULL;
DROP INDEX post_fi_1 ON post;
CREATE INDEX IDX_5A8A6C8DA76ED395 ON post (user_id);
ALTER TABLE sf_guard_group_permission ADD CONSTRAINT FK_EA8F2E83FE54D947 FOREIGN KEY (group_id) REFERENCES sf_guard_group (id);
ALTER TABLE sf_guard_group_permission ADD CONSTRAINT FK_EA8F2E83FED90CCA FOREIGN KEY (permission_id) REFERENCES sf_guard_permission (id);
ALTER TABLE sf_guard_remember_key ADD CONSTRAINT FK_1EEA28AA76ED395 FOREIGN KEY (user_id) REFERENCES sf_guard_user (id);
ALTER TABLE user CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE account_id account_id INT DEFAULT NULL;
ALTER TABLE user ADD CONSTRAINT FK_8D93D6499B6B5FBA FOREIGN KEY (account_id) REFERENCES sf_guard_user (id);
DROP INDEX user_fi_1 ON user;
CREATE INDEX IDX_8D93D6499B6B5FBA ON user (account_id);

SET FOREIGN_KEY_CHECKS = 1;
