 SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE sf_guard_remember_key DROP INDEX IDX_1EEA28AA76ED395, ADD UNIQUE INDEX UNIQ_1EEA28AA76ED395 (user_id);
ALTER TABLE sf_guard_remember_key DROP FOREIGN KEY sf_guard_remember_key_FK_1;
ALTER TABLE sf_guard_remember_key DROP PRIMARY KEY;
ALTER TABLE sf_guard_remember_key CHANGE user_id user_id INT DEFAULT NULL;
ALTER TABLE sf_guard_remember_key ADD CONSTRAINT FK_1EEA28AA76ED395 FOREIGN KEY (user_id) REFERENCES sf_guard_user (id);
ALTER TABLE sf_guard_remember_key ADD PRIMARY KEY (ip_address);
ALTER TABLE sf_guard_user CHANGE algorithm algorithm VARCHAR(128) NOT NULL, CHANGE is_active is_active TINYINT(1) NOT NULL, CHANGE is_super_admin is_super_admin TINYINT(1) NOT NULL;
ALTER TABLE sf_guard_user_group DROP FOREIGN KEY sf_guard_user_group_FK_1;
ALTER TABLE sf_guard_user_group DROP FOREIGN KEY sf_guard_user_group_FK_2;
ALTER TABLE sf_guard_user_group ADD CONSTRAINT FK_F2314A42A76ED395 FOREIGN KEY (user_id) REFERENCES sf_guard_user (id);
ALTER TABLE sf_guard_user_group ADD CONSTRAINT FK_F2314A42FE54D947 FOREIGN KEY (group_id) REFERENCES sf_guard_group (id);
ALTER TABLE sf_guard_user_permission DROP FOREIGN KEY sf_guard_user_permission_FK_1;
ALTER TABLE sf_guard_user_permission DROP FOREIGN KEY sf_guard_user_permission_FK_2;
ALTER TABLE sf_guard_user_permission ADD CONSTRAINT FK_418F0629A76ED395 FOREIGN KEY (user_id) REFERENCES sf_guard_user (id);
ALTER TABLE sf_guard_user_permission ADD CONSTRAINT FK_418F0629FED90CCA FOREIGN KEY (permission_id) REFERENCES sf_guard_permission (id);
ALTER TABLE subscription DROP FOREIGN KEY subscription_FK_1;
ALTER TABLE subscription CHANGE user_id user_id INT DEFAULT NULL;
ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE user DROP FOREIGN KEY user_FK_1;
ALTER TABLE user CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE account_id account_id INT DEFAULT NULL;
ALTER TABLE user ADD CONSTRAINT FK_8D93D6499B6B5FBA FOREIGN KEY (account_id) REFERENCES sf_guard_user (id);
SET FOREIGN_KEY_CHECKS=1;
