NAE\PlateformBundle\Entity\CmsEntry:
    type: entity
    table: cms_entry
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 31
            fixed: false
            comment: ''
        title:
            type: string
            nullable: true
            length: 127
            fixed: false
            comment: ''
        text:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
    lifecycleCallbacks: {  }
