NAE\PlateformBundle\Entity\Featurable:
    type: entity
    table: featurable
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        featuringDate:
            type: datetime
            nullable: true
            comment: ''
            column: featuring_date
        descendantClass:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: descendant_class
    lifecycleCallbacks: {  }
