NAE\PlateformBundle\Entity\NewsEntry:
    type: entity
    table: news_entry
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
    lifecycleCallbacks: {  }
