NAE\PlateformBundle\Entity\Picture:
    type: entity
    table: picture
    indexes:
        picture_FI_1:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 63
            fixed: false
            comment: ''
        description:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        price:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        path:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        exposable:
            type: boolean
            nullable: true
            comment: ''
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
        featuringDate:
            type: datetime
            nullable: true
            comment: ''
            column: featuring_date
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
