NAE\PlateformBundle\Entity\SfGuardRememberKey:
    type: entity
    table: sf_guard_remember_key
    indexes:
        IDX_1EEA28AA76ED395:
            columns:
                - user_id
    id:
        ipAddress:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            id: true
            column: ip_address
    fields:
        rememberKey:
            type: string
            nullable: true
            length: 32
            fixed: false
            comment: ''
            column: remember_key
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
    oneToOne:
        user:
            targetEntity: SfGuardUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
