NAE\PlateformBundle\Entity\SfGuardPermission:
    type: entity
    table: sf_guard_permission
    uniqueConstraints:
        sf_guard_permission_U_1:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    manyToMany:
        group:
            targetEntity: SfGuardGroup
            cascade: {  }
            mappedBy: permission
            inversedBy: null
            joinTable: null
            orderBy: null
        user:
            targetEntity: SfGuardUser
            cascade: {  }
            mappedBy: permission
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
