SfGuardGroup:
    type: entity
    table: sf_guard_group
    uniqueConstraints:
        sf_guard_group_U_1:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        description:
            type: text
            nullable: true
            length: null
            fixed: false
    manyToMany:
        permission:
            targetEntity: SfGuardPermission
            cascade: {  }
            mappedBy: null
            inversedBy: group
            joinTable:
                name: sf_guard_group_permission
                joinColumns:
                    -
                        name: group_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: permission_id
                        referencedColumnName: id
            orderBy: null
        user:
            targetEntity: SfGuardUser
            cascade: {  }
            mappedBy: group
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
