NAE\PlateformBundle\Entity\User:
    type: entity
    table: user
    indexes:
        user_FI_1:
            columns:
                - account_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        coverPictureId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: cover_picture_id
        firstName:
            type: string
            nullable: true
            length: 31
            fixed: false
            comment: ''
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 31
            fixed: false
            comment: ''
            column: last_name
        birthday:
            type: date
            nullable: true
            comment: ''
        category:
            type: string
            nullable: true
            length: 31
            fixed: false
            comment: ''
        biography:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        phone:
            type: string
            nullable: true
            length: 15
            fixed: false
            comment: ''
        country:
            type: string
            nullable: true
            length: 2
            fixed: false
            comment: ''
        featuringDate:
            type: datetime
            nullable: true
            comment: ''
            column: featuring_date
    manyToOne:
        account:
            targetEntity: SfGuardUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                account_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
