# NAE/PlateformBundle/Resources/config/admin.yml

services:
    sonata.admin.post:
        class: NAE\PlateformBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Textes" }
        arguments:
            - ~
            - NAE\PlateformBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [NAEPlateformBundle]]

    sonata.admin.news:
            class: NAE\PlateformBundle\Admin\NewsAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "News" }
            arguments:
                - ~
                - NAE\PlateformBundle\Entity\NewsEntry
                - ~
            calls:
                - [ setTranslationDomain, [NAEPlateformBundle]]
