# NAE/PlateformBundle/Resources/config/admin.yml

services:
    sonata.admin.post:
        class: NAE\PlateformBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateurs", label: "Post" }
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - NAE\PlateformBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [NAEPlateformBundle]]