nae_plateform_homepage:
    path:     /hello/
    defaults: { _controller: NAEPlateformBundle:Default:index }
    
# src/NAE/PlatformBundle/Resources/config/routing.yml

Newart:
    path:     /
    defaults: { _controller: NAEPlateformBundle:Expo:index }
    
nae_plateform_profil:
    path:     /profile/
    defaults: { _controller: NAEPlateformBundle:Default:profile }