# src/NAE/PlatformBundle/Resources/config/routing.yml

Newart:
    path:     /
    defaults: { _controller: NAEPlateformBundle:Expo:index }

nae_plateform_profil:
    path:     /profil/
    defaults: { _controller: NAEPlateformBundle:Expo:profil }

nae_plateform_books:
    path:     /books/
    defaults: { _controller: NAEPlateformBundle:Expo:books }

nae_plateform_expo:
    path:     /expo/
    defaults: { _controller: NAEPlateformBundle:Expo:expo }

nae_plateform_nae:
    path:     /nae/
    defaults: { _controller: NAEPlateformBundle:Expo:nae }

nae_plateform_contact:
    path:     /contact/
    defaults: { _controller: NAEPlateformBundle:Expo:contact }

nae_plateform_articles:
    path:     /articles/
    defaults: { _controller: NAEPlateformBundle:Expo:articles }

nae_plateform_article:
    path:     /article/
    defaults: { _controller: NAEPlateformBundle:Expo:article }

<<<<<<< HEAD
=======

>>>>>>> ce38a0e1906b0d69756e77455fbb8dfcbfd4cc25
