services:
    NAE_plateformBundle.post.listenenr:
        class: NAE\PlateformBundle\Listener\PostListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

